---
name: commands
version: 0.0.1
main: megarabyte\commands\Main
api: 5.10.0
src-namespace-prefix: megarabyte\commands
description: "Easier command validation"
author: Rishi
depend:
  - "messageservice"
