---
name: announcer
version: 0.0.1
main: megarabyte\announcer\Main
api: 5.10.0
src-namespace-prefix: megarabyte\announcer
author: Rishi
description: Broadcaster for announcements
depend:
  - "messageservice"
  - "permanentstorage"

commands:
  announcement:
    description: Add/remove/edit/view announcements
    usage: "/announcement <action> <name> [announcement]"
    permission: announcer.announcer

permissions:
  announcer.announcer:
    description: Able to modify announcements
    default: op
