---
name: permanentstorage
version: 0.0.1
main: megarabyte\permanentstorage\Main
api: 5.10.0
src-namespace-prefix: megarabyte\permanentstorage
author: Rishi
description: Allows files and databases to be stored permanently into plugins.
